### PR TITLE
Upload hw04

### PR DESCRIPTION
**Pull request by Naidantu**

### CODE REVIEW

**Comment by Naidantu** [comment]
@samruddhis @gregrousis

**Comment by gregrousis** [comment]
Looks like a cool project! Are the functions already fully written?

**Comment by Naidantu** [comment]
Thanks! @gregrousis  The main functions are completed but I still need to make some changes in the package based on Brenton's suggestions.

**Comment by samruddhis** [comment]
----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         |:heavy_check_mark:   |  |  |
**Presentation: graphs**    |  :heavy_check_mark: |  |  |
**Presentation: tables**    | :heavy_check_mark:  |   |  |
**Achievement, creativity** | :heavy_check_mark:  |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Your project sounds really interesting! I'm not really familiar with the methods you are using but the comments in your code were really helpful.

**Pull request merged**
